# -*- coding: utf-8 -*-
"""Tokenizer2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1NtJjNeKv0vJLTbWUm8LSBuVX2JlkuzWp
"""

!pip install keras keras_nlp tensorflow tensorflow-text

import keras, keras_nlp

tokenizer = keras_nlp.models.Tokenizer.from_preset("albert_base_en_uncased")

tokenizer("Bengaluru is the garden city of India")

tokenizer = keras_nlp.models.Tokenizer.from_preset("albert_large_en_uncased")

tokenizer("Bengaluru is the garden city of India")

tokenizer = keras_nlp.models.Tokenizer.from_preset("albert_extra_large_en_uncased")

tokenizer("Bengaluru is the garden city of India")

tokenizer = keras_nlp.models.Tokenizer.from_preset("albert_extra_extra_large_en_uncased")

tokenizer("Bengaluru is the garden city of India")

